apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EnforceRepos
metadata:
  name: repos-for-env
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "default"
  parameters:
    repos:
      - "rancher"
